import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className=" bg-gradient-to-b from-blue-100 to-red-100  ">
        <div className="h-20 px-20 ">
          <Navbar />
        </div>

        <div className="h-full w-full border-t-4 mt-4 border-white px-20">{children}</div>
        <div className="h-20 px-20">
          <Footer />
        </div>
      </body> */}
      <body className="flex flex-col min-h-screen bg-white ">
        <div className="h-20 px-20">
          <Navbar />
        </div>

        <div className="flex-1 px-20 border-t-4 mt-4 border-black">{children}</div>

        <div className="footer pt-8 bottom-0 w-full font-semibold ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
